apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: pcpb-graphql-api
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: kryllis/pcpb-graphql-api
    context: .
    docker:
      dockerfile: Dockerfile
      target: dev
    sync:
      manual:
      - src: '**/*.ts'
        dest: .
deploy:
  helm:
    flags:
      upgrade:
        - --install
    releases:
    - name: pcpb-graphql-api
      chartPath: pcpb-graphql-api
      values:
        image: kryllis/pcpb-graphql-api


# apiVersion: skaffold/v2alpha1
# kind: Config
# metadata:
#   name: pcpb
# build:
#   artifacts:
#   - image: kryllis/pcpb
#     context: .
#     docker:
#       dockerfile: Dockerfile
#       target: dev
#     sync:
#       manual:
#       - src: '**/*.ts'
#         dest: .




# deploy:
#   kubeContext: create
#   helm:
#     releases:
#     - name: pcpb
#       remote: false
#       chartPath: pcpb
#       namespace: default
#       version: 0.1.0
#       values: 
#         image: pcpb
# portForward:
#   - resourceType: deployment
#     resourceName: pcpb
#     namespace: default
#     port: 3000
#     localPort: 3010
